name: "Docker Image Build"

on:
  push:
    branches:
      - master
    paths:
      - "image/**"
      - ".github/workflows/image.yaml"

jobs:
  build:
    name:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Image'
        uses: actions/checkout@master
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: {{ '${{ secrets.AWS_ACCESS_KEY_ID }}' }}
          aws-secret-access-key: {{ '${{ secrets.AWS_SECRET_ACCESS_KEY }}' }}
          aws-region: {{ '${{ secrets.AWS_DEFAULT_REGION }}' }}
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: {{ '${{ steps.login-ecr.outputs.registry }}' }}
          ECR_REPOSITORY: crowdsmart-jupyterhub-dev-jupyterlab
          IMAGE_TAG: {{' ${{ github.sha }}' }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG image
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
      - name: Logout of Amazon ECR
        if: always()
        run: docker logout {{ '${{ steps.login-ecr.outputs.registry }}' }}
