name: "Docker Image Build - Pull Request"

on:
  pull_request:
    branches:
      - master
    paths:
      - "image/**"
      - ".github/workflows/image-pr.yaml"

jobs:
  jupyterlab:
    name:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Image'
        uses: actions/checkout@master
      - name: Build Image
        env:
          IMAGE_TAG: {{ '${{ github.sha }}' }}
        run: |
          docker build -f image/Dockerfile.qhub-jupyterlab -t qhub-jupyterlab:$IMAGE_TAG image

  dask-gateway:
    name:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Image'
        uses: actions/checkout@master
      - name: Build Image
        env:
          IMAGE_TAG: {{ '${{ github.sha }}' }}
        run: |
          docker build -f image/Dockerfile.dask-gateway -t qhub-dask-gateway:$IMAGE_TAG image

  dask-worker:
    name:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Image'
        uses: actions/checkout@master
      - name: Build Image
        env:
          IMAGE_TAG: {{ '${{ github.sha }}' }}
        run: |
          docker build -f image/Dockerfile.dask-worker -t qhub-dask-worker:$IMAGE_TAG image
