#!/usr/bin/env bash
set -euo pipefail

# install classic notebook extensions
jupyter nbextension enable --py widgetsnbextension --sys-prefix
jupyter serverextension enable --sys-prefix jupyter_server_proxy

# sets up jupyterlab-git
# lab extension will be built with jupyter lab build later
pip install --no-cache-dir \
    jupyterlab-git

# install jupyterlab extensions
jupyter labextension install --clean \
        dask-labextension \
        jupyterlab-cpustatus \
        @jupyter-widgets/jupyterlab-manager \

# ====== cleanup labextension install =======
rm -rf ${HOME}/.cache ${HOME}/.npm ${HOME}/.yarn
rm -rf /opt/conda/share/jupyter/lab/staging
find /opt/conda -follow -type f -name '*.js.map' -delete

# ====== setup ipython conifiguration ======
mkdir /etc/ipython
cp /opt/jupyterlab/ipython_config.py /etc/ipython/ipython_config.py